from .CroniclException import CroniclException

class ValidationError(CroniclException): pass